### ISSUE TITLE
第二回まとめ作成

### ISSUE THREAD

**Issue by krhrtky** [hr-js/learn_js_function#2]
### 書いてほしいこと

+ やったこと、学んだこと

+ 特にテキストだと分かならなかったこととか思ったこととかも書けるとGood!

+ [一回目のまとめ](https://github.com/hr-js/learn_js_function/blob/master/doc/minutes_1.md) の書き方で参考になるところがあれば、流用してね。

### その他参考資料

+ [markdown書き方01](https://gist.github.com/wate/7072365)

+ [markdown書き方02](https://qiita.com/tbpgr/items/989c6badefff69377da7)

+ 分かんないこととかは都度都度、issueでも何でもいいから聞いてサクサク進めましょう！

**Comment by Tchikawa** [comment]
終わったです〜
