### ISSUE TITLE
12/1(Fri) 開催分のまとめ

### ISSUE THREAD

**Issue by krhrtky** [hr-js/learn_js_function#4]
## 12/1(Fri) 開催分のまとめを書いてみよう

# まとめ方

* #2 を参考にまとめを書いてみよう！

* 書き方、JSでわからないことは、ここで聞いて！

* 本格入門持ってないから、その部分も聞いてもらうか、子サイで代用って感じで！

**Comment by minako-nakanishi** [comment]
プルリク出しました。よろしくお願いします。

**Comment by minako-nakanishi** [comment]
修正分のプルリク出しました。よろしくお願いします。
